apiVersion: v1
kind: ServiceAccount

metadata:
  name: day2-vault
  namespace: openshift-gitops

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth

metadata:
  name: day2-vault-auth
  namespace: openshift-gitops

spec:
  vaultConnectionRef: day2-vault

  method: kubernetes

  mount: kubernetes

  kubernetes:
    role: ztp3-day2
    serviceAccount: day2-vault
    audiences:
      - vault
