apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret

metadata:
  name: cluster-config-repository
  namespace: openshift-gitops

spec:
  vaultAuthRef: day2-vault-auth

  mount: acm
  type: kv-v2

  path: ztp3/day2/git

  refreshAfter: 1h

  destination:
    name: cluster-config-repository

    create: true
    overwrite: true

    type: Opaque

    labels:
      argocd.argoproj.io/secret-type: repository
