apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig

metadata:
  name: ztp3-worker-2
  namespace: ztp3

  labels:
    ztp3-nmstate: "true"

spec:

  interfaces:

    - name: eno1
      macAddress: "CHANGE_ME_WORKER2_NIC1"

    - name: eno2
      macAddress: "CHANGE_ME_WORKER2_NIC2"

  config:

    interfaces:

      - name: eno1
        type: ethernet
        state: up

        ipv4:
          enabled: true
          dhcp: false

          address:
            - ip: 192.168.1.205
              prefix-length: 24

      - name: eno2
        type: ethernet
        state: up

        ipv4:
          enabled: true
          dhcp: false

          address:
            - ip: 10.10.10.205
              prefix-length: 24

    dns-resolver:
      config:
        server:
          - 192.168.1.1

    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.1.1
          next-hop-interface: eno1
          table-id: 254
