apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ztp
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ztp-cluster
    serviceAccount: ztp-vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ztp-secrets
spec:
  type: kv-v2
  mount: secret
  path: ztp/cluster01

  destination:
    name: ztp-secrets
    create: true

  vaultAuthRef: ztp
