apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Cluster
  - cluster/agentclusterinstall.yaml
  - cluster/infraenv.yaml
  - cluster/managedcluster.yaml
  - cluster/klusterletaddonconfig.yaml

  # Secrets
  - secrets/bmc-secret.yaml
  - secrets/pull-secret.yaml

  # Control plane
  - baremetalhosts/control-plane/master-0.yaml
  - baremetalhosts/control-plane/master-1.yaml
  - baremetalhosts/control-plane/master-2.yaml

  # Workers
  - baremetalhosts/workers/worker-0.yaml
  - baremetalhosts/workers/worker-1.yaml
  - baremetalhosts/workers/worker-2.yaml
