apiVersion: v1
kind: ServiceAccount

metadata:
  name: provisioning-vault
  namespace: ztp3

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth

metadata:
  name: provisioning-vault-auth
  namespace: ztp3

spec:
  vaultConnectionRef: provisioning-vault

  method: kubernetes

  mount: kubernetes

  kubernetes:
    role: ztp3-provisioning
    serviceAccount: provisioning-vault
    audiences:
      - vault
