apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection

metadata:
  name: provisioning-vault
  namespace: ztp3

spec:
  address: "http://VAULT_ADDRESS:8200"

  # Set this to false when using a trusted TLS certificate.
  skipTLSVerify: true
