apiVersion: v1
kind: Secret

metadata:
  name: pull-secret
  namespace: ztp3

type: kubernetes.io/dockerconfigjson

stringData:

  .dockerconfigjson: |
    {
      "auths": {
        "cloud.openshift.com": {
          "auth": "CHANGE_ME"
        },
        "registry.redhat.io": {
          "auth": "CHANGE_ME"
        },
        "quay.io": {
          "auth": "CHANGE_ME"
        }
      }
    }
