apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-automation-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/olawale241/gitops.git'
    targetRevision: main
    path: AAP/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ansible-automation-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

