apiVersion: metal3.io/v1alpha1
kind: BareMetalHost

metadata:
  name: ztp3-worker-0
  namespace: ztp3

  annotations:
    bmac.agent-install.openshift.io/cluster-reference: ztp3/ztp3
    bmac.agent-install.openshift.io/hostname: ztp3-worker-0
    bmac.agent-install.openshift.io/role: worker

  labels:
    infraenvs.agent-install.openshift.io: ztp3
    node-role.kubernetes.io/worker: ""

spec:

  online: true

  bootMode: UEFI

  bootMACAddress: "CHANGE_ME"

  bmc:
    address: "CHANGE_ME"
    credentialsName: bmc-credentials
    disableCertificateVerification: true

  automatedCleaningMode: disabled

  rootDeviceHints:
    deviceName: /dev/sda
