apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ .Values.kafkaCluster.name }}
spec:
  replicas: {{ .Values.kafkaCluster.replicas.broker }}
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafkaCluster.storage.size }}
        kraftMetadata: shared
        deleteClaim: false
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - {{ .Values.kafkaCluster.name }}-kafka
              topologyKey: "kubernetes.io/hostname"
