apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  channel: stable
  installPlanApproval: Automatic
  name: external-secrets
  source: community-operators
  sourceNamespace: openshift-marketplace
