apiVersion: hive.openshift.io/v1
kind: ClusterDeployment

metadata:
  name: cluster
  namespace: cluster

spec:
  baseDomain: example.com

  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: cluster
    version: v1beta1

  clusterName: cluster

  controlPlaneConfig:
    servingCertificates: {}

  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster: cluster

  pullSecretRef:
    name: pull-secret
