apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv

metadata:
  name: ztp3
  namespace: ztp3

spec:

  clusterRef:
    name: ztp3
    namespace: ztp3

  cpuArchitecture: x86_64

  pullSecretRef:
    name: pull-secret

  sshAuthorizedKey: "CHANGE_ME_SSH_PUBLIC_KEY"

  nmStateConfigLabelSelector:
    matchLabels:
      ztp3-nmstate: "true"
