apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ztp3

resources:
  - vault-hub-clusterrolebinding.yaml
  - vault-hub-sa.yaml
  - vault-hub-clusterrole.yaml
  - vault-hub-configmap.yaml
  - vault-hub-job.yaml
  - vault-hub-secret.yaml
